### PR TITLE
Fixed autoformat configuration

### LINKED ISSUE #74: scalariform broken in multiproject setups
The `processed` `AtomicBoolean` logic in `SbtScalariform` means that Scalariform settings only get applied to the first sub project that the scalariform autoplugin is enabled on. Every subsequent subproject, when `projectSettings` is invoked, will return `Nil`, and so scalariform won't be enabled for those subprojects.

The issue that the comment says it's working around is a non issue, the problem is that the approach scaliform is trying to use to disable automatically running scalariform is not working with the way sbt works. You can't disable something by not setting it if a plugin has already set it, you can only disable it by overriding what the plugin has already set. So, instead, what scalariform should provide, is a setting, eg `scalariformAutoformat: SettingKey[Boolean]`, then the redefinition of `compileInputs` should read this and use a dynamic task to trigger scalariform if set.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #74

Autoformat is now configured the way sbt is meant to be used (ie, using a setting).

Also put global settings in the auto plugin global settings, rather than putting them into the project settings. Also modified IT settings so that they only add it scoped settings (since the test and compile settings are already added automatically via projectSettings, so no need to add them twice when configuring IT settings).

### CODE REVIEW

File: src/main/scala/com/typesafe/sbt/SbtScalariform.scala [hunk 1]
```diff
@@ -31,69 +31,48 @@ object SbtScalariform
...
-    }
+    def scalariformItSettings: Seq[Setting[_]] = inputs(It) ++ inConfig(It)(configScalariformSettings)
   }
   import autoImport._
 
+  override def globalSettings = Seq(
+    scalariformPreferences := defaultPreferences,
+    includeFilter in scalariformFormat := "*.scala",
+    scalariformAutoformat := PreferencesFile(None).forall(_.autoformat.autoformat)
+  )
```
Comment (jroper) [inline src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: Not sure that Global is the right scope for these, they probably should be defined at the build scope.

Comment (godenji) [reply src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: > Not sure that Global is the right scope for these

Let's leave as is for now, can look into changing before publishing a release -- have to sort out another issue with Play generated sources (router *.scala files) being reformatted on every `compile`, and then we should be good for 1.8.2

**Comment by godenji** [comment]
@jroper fantastic, thanks for getting rid of the ugly hack.

File: src/main/scala/com/typesafe/sbt/SbtScalariform.scala (hunk 1 above)
Comment (jroper) [reply src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: Really? As far as I can see it's only including `unmanagedSourceDirectories`, which should mean the router files aren't reformatted, unless the Play routes compiler is adding its output directory to `unmanagedSourceDirectories`, which would be really bad if it is.

Comment (godenji) [reply src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: It was [another change](https://github.com/sbt/sbt-scalariform/commit/42ca0f04b5e7280afcf8eec896580f141be85891), spurred on by users wanting to have sources in project root (including build def) formatted.

Unfortunately generated play router sources also live in the root (compile target), which causes scalariform to format the sources, which in turn causes Play to recompile the sources as they've changed since last compilation.

Apparently one possible fix is using `ThisProject` in place of `LocalRootProject`.

Comment (eed3si9n) [reply src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: The use of global scope is perfectly fine for plugins to use as long as it's on your own key or task scoping, and there is zero chance of conflicting with either the default settings provided by others (like sbt's JvmPlugin).

Comment (jroper) [reply src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: Is global scope basically `ThisBuild` + whatever `~/.sbt/<version>/*.sbt` defines? Or can global scope also impact settings in other build units? If it's the former, then global scope is probably the right idea - it means that users can add scalariform to their global plugins and configure it there (though there's probably many down sides of doing that).

Comment (eed3si9n) [reply src/main/scala/com/typesafe/sbt/SbtScalariform.scala]: As far as I know, global scope just means `in Global` aka `in (Zero, Zero, Zero)` for all axes, so just strictly weakest scope. In practice, I don't think it matters all that much if a plugin used `buildSettings` or `globalSettings`, because to make a difference we'd need to use source-dependency where `{some-uri}/scalariformPreferences ` value is set differently from `{.}/scalariformPreferences `.
